services:
  spark:
    image: minsusun/spark-cluster-master:3.3.0
    container_name: master
    security_opt:
      - seccomp:unconfined
    privileged: true
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '7077:7077'
      - '8080:8080'
    volumes:
      - '/tmp/:/var/tmp/'
  spark-worker:
    image: minsusun/spark-cluster-worker:3.3.0
    security_opt:
      - seccomp:unconfined
    privileged: true
    environment:
      - SPARK_MASTER=spark://spark:7077
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - 8081-8090:8081
    deploy:
      replicas: 3

