apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: bde2020/spark-master:3.3.0-hadoop3.3
        securityContext:
          privileged: true
        ports:
        - name: dashboard
          containerPort: 8080
        - name: job
          containerPort: 7077
        env:
        - name: INIT_DAEMON_STEP
          value: setup_spark
        - # 원래 기존 이미지에서 환경변수를 지정해서 설정해놨지만, k8s로 올리면 이상하게 tcp://<ip_address>:8080으로 잡힌다
          # 강제로 7077으로 변경
          # > k8s에서 pod 생성시 k8s이 자동으로 SPARK_MASTER_PORT=<POD_IP>:<PORT>와 같이 환경변수를 세팅해서 생기는 문제.
          # 이름은 SPARK_MASTER가 아닌 걸로 바꾸면 되지만 귀찮으니 이대로 진행. 서비스를 붙이는 것때문에 생기는 이슈
          name: SPARK_MASTER_PORT
          value: "7077"
        - name: K8S_SPARK_MASTER_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      securityContext: {}
