apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
spec:
  selector:
    app: spark-history-server
  ports:
    - name: dashboard
      protocol: TCP
      port: 18081
      targetPort: http
