apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spark-cluster
resources:
  - ./k8s-spark-master.yaml
  - ./k8s-spark-master-service.yaml
  - ./k8s-spark-worker.yaml
  - ./k8s-spark-history-server.yaml
  - ./k8s-spark-history-server-service.yaml
